displayName=Chess
author=playercoder1
description=Play local or private two-player chess in the sidebar or an interactive game overlay
tags=chess
version=1.0
plugins=com.playercoder1.ChessPlugin
build=standard